#cloud-config
#
# Studycapt VM Autoinstall File
# For Ubuntu Budgie 26.04 LTS only.
#
# This autoconfig file sets up an Ubuntu Budgie system for
#  evaluating and debugging captdriver and CUPS
#
# Adapted from /var/log/installer/autoinstall-user-data
# Edited by Moses Chong, 2026-06-08
# License: CC0, https://creativecommons.org/publicdomain/zero/1.0/
#
# References
# ==========
# Autoinstall documentation: https://canonical-subiquity.readthedocs-hosted.com/en/latest/reference/autoinstall-reference.html
#
autoinstall:
  apt:
    disable_components: []
    fallback: offline-install
    geoip: true
    mirror-selection:
      primary:
      - country-mirror
      - arches:
        - amd64
        - i386
        uri: http://archive.ubuntu.com/ubuntu/
    preserve_sources_list: false
    security:
    - arches:
      - amd64
      - i386
      uri: http://security.ubuntu.com/ubuntu/
  codecs:
    install: false
  drivers:
    install: false
  interactive-sections:
    - storage
    - identity
  kernel:
    package: linux-generic-hwe-24.04
  keyboard:
    layout: us
    toggle: null
    variant: ''
  locale: en_US.UTF-8
  oem:
    install: auto
  packages:
    - libcups2-dev
    - libavahi-client-dev
    - libkrb5-dev
    - libnss-mdns
    - libpam-dev
    - libssl-dev
    - libsystemd-dev
    - libusb-1.0-0-dev
    - avahi-daemon
    - atril
    - automake
    - build-essential
    - gimp
    - git
    - inkscape
    - libreoffice
    - vim-gtk3
    - wireshark
    - zlib1g-dev
  source:
    id: ubuntu-budgie-desktop-minimal
    search_drivers: false
  ssh:
    allow-pw: false
    authorized-keys: []
    install-server: false
  timezone: UTC
  updates: security
  version: 1
