#cloud-config
#
# Studycapt VM Autoinstall File
# For Ubuntu Budgie 26.04 LTS on x86_64 only.
# Installation will fail on other Ubuntu flavours or
#   instruction set architectures.
#
# Adapted from /var/log/installer/autoinstall-user-data
# Edited by Moses Chong, 2026-06-08
# License: CC0, https://creativecommons.org/publicdomain/zero/1.0/
#
# This autoconfig helps set up an Ubuntu VM for analysing
# the CAPT protocol and associated data formats.
# Package choices has been tweaked for Ubuntu Budgie.
#
# Security Advice and Password
# ============================
# Password is HP_IS_BETTER, please change this even if
# you are running in a VM. If a VM is compromised via the
# internet using this password, it may affect the host
# system by way of shared directories.
#
# References
# ==========
# Autoinstall documentation: https://canonical-subiquity.readthedocs-hosted.com/en/latest/reference/autoinstall-reference.html
#
# TODO: Can i386 packages be added in the packages section,
#   or are we stuck with using curtin in-target late commands?
#
autoinstall:
  apt:
    disable_components: []
    fallback: offline-install
    geoip: true
    mirror-selection:
      primary:
      - country-mirror
      - arches:
        - amd64
        - i386
        uri: http://archive.ubuntu.com/ubuntu/
    preserve_sources_list: false
    security:
    - arches:
      - amd64
      - i386
      uri: http://security.ubuntu.com/ubuntu/
  codecs:
    install: false
  drivers:
    install: false
  identity:
    hostname: capthacker-pc
    password: $6$kBZ8Kq9i49dTfBbY$cK/Gl64PBJGcdCaed3QgWQRqwUgtQbZTxXwC2M0pikdrf/dOxMGlhkPF48JCmjEdj68sZ2.0FRuM9XEIB0DPV0
    realname: capthacker
    username: capthacker
  interactive-sections:
    - storage
  kernel:
    package: linux-generic-hwe-24.04
  keyboard:
    layout: us
    toggle: null
    variant: ''
  late-commands:
    - curtin in-target -- dpkg --add-architecture i386
    - curtin in-target -- apt-get update
    - curtin in-target -- apt-get install -y libatk1.0-0t64:i386 libc6:i386 libcairo2:i386 libgtk2.0-0t64:i386 libpango-1.0-0:i386 libpopt0:i386 libstdc++6:i386 libxml2-16:i386
  locale: en_US.UTF-8
  oem:
    install: auto
  packages:
    - atril
    - automake
    - build-essential
    - drawing
    - git
    - inkscape
    - libcups2-dev
    - libreoffice
    - vim-gtk3
    - wireshark
  source:
    id: ubuntu-budgie-desktop-minimal
    search_drivers: false
  ssh:
    allow-pw: false
    authorized-keys: []
    install-server: false
  timezone: UTC
  updates: security
  version: 1
